name: Build Mozc (Windows ARM64)

on:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install Git (if missing) and Chocolatey (optional)
        run: |
          where git || choco install git -y

      - name: Install depot_tools
        shell: pwsh
        run: |
          $dest = "${env:RUNNER_TEMP}\depot_tools"
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools $dest
          echo "::add-path::$dest"
          # Ensure depot_tools python wrapper is used
          setx PATH "$($env:PATH);$dest"

      - name: Prepare workspace and gclient config
        shell: pwsh
        run: |
          mkdir C:\work
          cd C:\work
          md mozc -Force
          cd mozc
          # Configure gclient to point to the GitHub mirror (or google/mozc)
          gclient config https://github.com/google/mozc.git --name=. --deps-file=src/DEPS

      - name: gclient sync (fetch deps)
        shell: pwsh
        run: |
          cd C:\work\mozc
          gclient sync --with_branch_heads

      - name: Generate projects (GYP)
        shell: pwsh
        run: |
          cd C:\work\mozc\src
          python build_mozc.py gyp --noqt --gyp_generator=ninja

      - name: Build and package (Release)
        shell: pwsh
        run: |
          cd C:\work\mozc\src
          python build_mozc.py build -c Release package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mozc-windows-arm64
          path: C:\work\mozc\src\out\**
